var micachorro = { raza: "shitzu" };
console.log("la raza de mi cahorro es:" + micachorro.raza);
var micachorro2 = { raza2: "shitzu" };
console.log("la raza de mi cahorro es:" + micachorro2.raza2);
micachorro.raza2 = 'pitbull';
var luis = { edad: 20 };
var pedro = luis;
luis.edad++;
console.log(luis);
console.log(pedro);
